package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Domain;

import java.util.List;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(Domain record);

    Long selectMaxId();

    Domain selectByName(String name);

    Domain selectById(Long id);

    List<Domain> selectDomain();

    String selectNameById(Long id);
}