package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.EvolutionBusiness;

public interface EvolutionBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evolution_business
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    int insert(EvolutionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evolution_business
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    int insertSelective(EvolutionBusiness record);
}