package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.EvolutionUsecase;

public interface EvolutionUsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evolution_usecase
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    int insert(EvolutionUsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evolution_usecase
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    int insertSelective(EvolutionUsecase record);
}