package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.QuestionBusiness;

public interface QuestionBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(QuestionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(QuestionBusiness record);
}