package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.QuestionUsecase;

public interface QuestionUsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(QuestionUsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(QuestionUsecase record);
}