package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Review;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(Review record);

    Long selectMaxId();
}