package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestion;

public interface SolutionQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(SolutionQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(SolutionQuestion record);
}