package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseBusiness;

public interface UsecaseBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(UsecaseBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(UsecaseBusiness record);
}