package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseRole;
import org.apache.ibatis.annotations.Param;
import org.springframework.beans.factory.annotation.Qualifier;

import java.util.List;

public interface UsecaseRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(UsecaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(UsecaseRole record);

    int insertRoleIdsandProjectId(@Param("roleIds")List<Long> roleIds,@Param("projectId")Long projectId);

    Long  selectMaxId();

//    List<Long> selectUsecaseIdsByRoleIds(@Param("roleIds")List<Long> roleIds);

}