package cn.edu.buaa.rec.model;

import java.util.Date;

public class Business {

    private Long id;

    private String name;

    private Date buildTime;

    private Date updateTime;

    private Long creatorId;

    private String priority;

    private String preCondition;

    private String postCondition;

    private String include;

    private String data;

    private String des;

    private String useState;

    private String description;

    private String flow;

    private Long projectId;

    private String input;

    private String output;

    private String dataDictionary;
    private String roles;


    public Business(String name, String description, Long creatorId, Long projectId) {
        this.name = name;
        this.description = description;
        this.creatorId = creatorId;
        this.projectId = projectId;
    }

    public Business(String name, String description, Long creatorId, Long projectId, String priority, String preCondition, String postCondition
            , String input, String output, String useState, String data, String role, String include, String des) {
        this.name = name;
        this.description = description;
        this.creatorId = creatorId;
        this.projectId = projectId;
        this.priority = priority;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.input = input;
        this.output = output;

        this.data = data;
        this.include = include;
        this.useState = useState;
        this.roles = role;
        this.des = des;
    }

    public Business(Long id, String name, String description, Long creatorId, Long projectId, String priority, String preCondition, String postCondition
            , String input, String output, String useState, String data, String role, String include, String des, String flow) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.creatorId = creatorId;
        this.projectId = projectId;
        this.priority = priority;
        this.preCondition = preCondition;
        this.postCondition = postCondition;
        this.input = input;
        this.output = output;

        this.data = data;
        this.include = include;
        this.useState = useState;
        this.roles = role;
        this.des = des;
        this.flow = flow;
    }


    public String getDataDictionary() {
        return dataDictionary;
    }

    public void setDataDictionary(String dataDictionary) {
        this.dataDictionary = dataDictionary;
    }

    public String getRoles() {
        return roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public Business() {
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.flow
     *
     * @return the value of business.flow
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.flow
     *
     * @param flow the value for business.flow
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setFlow(String flow) {
        this.flow = flow == null ? null : flow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.build_time
     *
     * @return the value of business.build_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.build_time
     *
     * @param buildTime the value for business.build_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.update_time
     *
     * @return the value of business.update_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.update_time
     *
     * @param updateTime the value for business.update_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.creator_id
     *
     * @return the value of business.creator_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.creator_id
     *
     * @param creatorId the value for business.creator_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.priority
     *
     * @return the value of business.priority
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.priority
     *
     * @param priority the value for business.priority
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.pre_condition
     *
     * @return the value of business.pre_condition
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getPreCondition() {
        return preCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.pre_condition
     *
     * @param preCondition the value for business.pre_condition
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setPreCondition(String preCondition) {
        this.preCondition = preCondition == null ? null : preCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.post_condition
     *
     * @return the value of business.post_condition
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getPostCondition() {
        return postCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.post_condition
     *
     * @param postCondition the value for business.post_condition
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setPostCondition(String postCondition) {
        this.postCondition = postCondition == null ? null : postCondition.trim();
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.use_state
     *
     * @return the value of business.use_state
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.use_state
     *
     * @param useState the value for business.use_state
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUseState(String useState) {
        this.useState = useState == null ? null : useState.trim();
    }

    public String getInclude() {
        return include;
    }

    public String getData() {
        return data;
    }

    public String getDes() {
        return des;
    }

    public void setInclude(String include) {
        this.include = include;
    }

    public void setData(String data) {
        this.data = data;
    }

    public void setDes(String des) {
        this.des = des;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    public String getOutput() {
        return output;
    }

    public void setOutput(String output) {
        this.output = output;
    }

}