package cn.edu.buaa.rec.model;

public class BusinessData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_data.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_data.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_data.data_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long dataId;

    public BusinessData() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_data.id
     *
     * @return the value of business_data.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_data.id
     *
     * @param id the value for business_data.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_data.business_id
     *
     * @return the value of business_data.business_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_data.business_id
     *
     * @param businessId the value for business_data.business_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_data.data_id
     *
     * @return the value of business_data.data_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_data.data_id
     *
     * @param dataId the value for business_data.data_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}