package cn.edu.buaa.rec.model;

public class BusinessRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_role.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_role.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_role.role_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long roleId;

    public BusinessRole() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_role.id
     *
     * @return the value of business_role.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_role.id
     *
     * @param id the value for business_role.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_role.business_id
     *
     * @return the value of business_role.business_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_role.business_id
     *
     * @param businessId the value for business_role.business_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_role.role_id
     *
     * @return the value of business_role.role_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_role.role_id
     *
     * @param roleId the value for business_role.role_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }


}