package cn.edu.buaa.rec.model;

import java.sql.Date;

public class Domain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.name
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.build_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.update_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.use_state
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String useState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.isApproved
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Integer isapproved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain.description
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String description;

    private String typicalData;

    @Override
    public String toString() {
        return "Domain{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", creatorId=" + creatorId +
                ", buildTime=" + buildTime +
                ", updateTime=" + updateTime +
                ", useState='" + useState + '\'' +
                ", isapproved=" + isapproved +
                ", typicalData='" + typicalData + '\'' +
                ", typicalRole='" + typicalRole + '\'' +
                ", typicalScenario='" + typicalScenario + '\'' +
                '}';
    }

    public String getTypicalData() {
        return typicalData;
    }

    public void setTypicalData(String typicalData) {
        this.typicalData = typicalData;
    }

    public String getTypicalRole() {
        return typicalRole;
    }

    public void setTypicalRole(String typicalRole) {
        this.typicalRole = typicalRole;
    }

    public String getTypicalScenario() {
        return typicalScenario;
    }

    public void setTypicalScenario(String typicalScenario) {
        this.typicalScenario = typicalScenario;
    }

    private String typicalRole;
    private String typicalScenario;

    public Domain(String name, String description, Long creatorId) {
        this.name = name;
        this.description = description;
        this.creatorId = creatorId;
    }

    public Domain() {
    }

    public Domain(Long id, String name, Long creatorId, Date buildTime, Date updateTime, String useState, Integer isapproved, String description) {
        this.id = id;
        this.name = name;
        this.creatorId = creatorId;
        this.buildTime = buildTime;
        this.updateTime = updateTime;
        this.useState = useState;
        this.isapproved = isapproved;
        this.description = description;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.id
     *
     * @return the value of domain.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.id
     *
     * @param id the value for domain.id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.name
     *
     * @return the value of domain.name
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.name
     *
     * @param name the value for domain.name
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.creator_id
     *
     * @return the value of domain.creator_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.creator_id
     *
     * @param creatorId the value for domain.creator_id
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.build_time
     *
     * @return the value of domain.build_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.build_time
     *
     * @param buildTime the value for domain.build_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.update_time
     *
     * @return the value of domain.update_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.update_time
     *
     * @param updateTime the value for domain.update_time
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.use_state
     *
     * @return the value of domain.use_state
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.use_state
     *
     * @param useState the value for domain.use_state
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUseState(String useState) {
        this.useState = useState == null ? null : useState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.isApproved
     *
     * @return the value of domain.isApproved
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Integer getIsapproved() {
        return isapproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.isApproved
     *
     * @param isapproved the value for domain.isApproved
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setIsapproved(Integer isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain.description
     *
     * @return the value of domain.description
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain.description
     *
     * @param description the value for domain.description
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}