package cn.edu.buaa.rec.model;

public class EvolutionBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evolution_business.id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evolution_business.business_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evolution_business.question_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evolution_business.solution_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    private Long solutionId;

    public EvolutionBusiness() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evolution_business.id
     *
     * @return the value of evolution_business.id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evolution_business.id
     *
     * @param id the value for evolution_business.id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evolution_business.business_id
     *
     * @return the value of evolution_business.business_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evolution_business.business_id
     *
     * @param businessId the value for evolution_business.business_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evolution_business.question_id
     *
     * @return the value of evolution_business.question_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evolution_business.question_id
     *
     * @param questionId the value for evolution_business.question_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evolution_business.solution_id
     *
     * @return the value of evolution_business.solution_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public Long getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evolution_business.solution_id
     *
     * @param solutionId the value for evolution_business.solution_id
     *
     * @mbggenerated Mon Mar 05 22:34:37 CST 2018
     */
    public void setSolutionId(Long solutionId) {
        this.solutionId = solutionId;
    }
}