package cn.edu.buaa.rec.model;

import java.sql.Date;

public class Project {

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.build_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.domain_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.function
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String function;

    @Override
    public String toString() {
        return "Project{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", buildTime=" + buildTime +
                ", updateTime=" + updateTime +
                ", creatorId=" + creatorId +
                ", domainId=" + domainId +
                ", function='" + function + '\'' +
                '}';
    }

    public Project() {
        System.out.println(1);
    }

    public Project(String name, String description, Long domainId, Long creatorId) {
        this.name = name;
        this.description = description;
        this.domainId = domainId;
        this.creatorId = creatorId;
    }

    public Project(Long id, String name, String description, Date buildTime, Date updateTime, Long creatorId, Long domainId, String function) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.buildTime = buildTime;
        this.updateTime = updateTime;
        this.creatorId = creatorId;
        this.domainId = domainId;
        this.function = function;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public Date getBuildTime() {
        return buildTime;
    }

    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    public Long getDomainId() {
        return domainId;
    }

    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    public String getFunction() {
        return function;
    }

    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

}