package cn.edu.buaa.rec.model;

public class QuestionBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_business.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    public QuestionBusiness() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_business.id
     *
     * @return the value of question_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_business.id
     *
     * @param id the value for question_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_business.question_id
     *
     * @return the value of question_business.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_business.question_id
     *
     * @param questionId the value for question_business.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_business.business_id
     *
     * @return the value of question_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_business.business_id
     *
     * @param businessId the value for question_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }
}