package cn.edu.buaa.rec.model;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.type_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Integer typeScenario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.sub_topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long subTopicId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String creatorName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date time;

    private Long approve;

    private Long diss;

    public String getCreatorName() {
        return creatorName;
    }

    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }

    public Long getApprove() {
        return approve;
    }

    public void setApprove(Long approve) {
        this.approve = approve;
    }

    public Long getDiss() {
        return diss;
    }

    public void setDiss(Long diss) {
        this.diss = diss;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String content;

    public Review() {
    }

    public Review(String creatorName,String content,int typeScenario) {
        this.content = content;
        this.creatorName = creatorName;
        this.typeScenario = typeScenario;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.type_scenario
     *
     * @return the value of review.type_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Integer getTypeScenario() {
        return typeScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.type_scenario
     *
     * @param typeScenario the value for review.type_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setTypeScenario(Integer typeScenario) {
        this.typeScenario = typeScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.business_id
     *
     * @return the value of review.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.business_id
     *
     * @param businessId the value for review.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.usecase_id
     *
     * @return the value of review.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.usecase_id
     *
     * @param usecaseId the value for review.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.topic_id
     *
     * @return the value of review.topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.topic_id
     *
     * @param topicId the value for review.topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.sub_topic_id
     *
     * @return the value of review.sub_topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getSubTopicId() {
        return subTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.sub_topic_id
     *
     * @param subTopicId the value for review.sub_topic_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setSubTopicId(Long subTopicId) {
        this.subTopicId = subTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.type
     *
     * @return the value of review.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.time
     *
     * @return the value of review.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.time
     *
     * @param time the value for review.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}