package cn.edu.buaa.rec.model;

import java.util.Date;

public class Solution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.title
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.build_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.update_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.project_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String content;

    private int flag;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.id
     *
     * @return the value of solution.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.id
     *
     * @param id the value for solution.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.title
     *
     * @return the value of solution.title
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.title
     *
     * @param title the value for solution.title
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.build_time
     *
     * @return the value of solution.build_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.build_time
     *
     * @param buildTime the value for solution.build_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.update_time
     *
     * @return the value of solution.update_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.update_time
     *
     * @param updateTime the value for solution.update_time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.creator_id
     *
     * @return the value of solution.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.creator_id
     *
     * @param creatorId the value for solution.creator_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.project_id
     *
     * @return the value of solution.project_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.project_id
     *
     * @param projectId the value for solution.project_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.type
     *
     * @return the value of solution.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.type
     *
     * @param type the value for solution.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.content
     *
     * @return the value of solution.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.content
     *
     * @param content the value for solution.content
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public int getFlag() {
        return flag;
    }

    public void setFlag(int flag) {
        this.flag = flag;
    }

    public Solution() {
    }

    public Solution(String title , String content , Long creatorId , Long projectId , Integer type , Integer flag ){
        this.title = title;
        this.content = content;
        this.creatorId = creatorId;
        this.projectId = projectId;
        this.type = type;
        this.flag = flag;
    }

    @Override
    public String toString() {
        return "Solution{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", buildTime=" + buildTime +
                ", updateTime=" + updateTime +
                ", creatorId=" + creatorId +
                ", projectId=" + projectId +
                ", type=" + type +
                ", content='" + content + '\'' +
                ", flag='" + flag + '\'' +
                '}';
    }
}