package cn.edu.buaa.rec.model;

public class SysUser {
    private Long id;

    private String name;

    private String phone;

    private String email;

    private String password;

    public String getFamiliardomain() {
        return familiardomain;
    }

    public void setFamiliardomain(String familiardomain) {
        this.familiardomain = familiardomain;
    }

    private String familiardomain;

    private String projectexp;

    public SysUser() {
    }

    @Override
    public String toString() {
        return "SysUser{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", familiardomain='" + familiardomain + '\'' +
                ", projectexp='" + projectexp + '\'' +
                '}';
    }

    public SysUser(String sysUserName, String phone, String email, String password) {
        this.name = sysUserName;
        this.phone = phone;
        this.email = email;
        this.password = password;
    }

    public SysUser(Long sysUserId, String sysUserName, String phone, String email, String password) {
        this.id = sysUserId;
        this.name = sysUserName;
        this.phone = phone;
        this.email = email;
        this.password = password;
    }

    public SysUser(Long id, String name, String phone, String email, String password, String projectexp) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.password = password;
        this.projectexp = projectexp;
    }

    public SysUser(Long id, String name, String phone, String email, String password,String familiarDomain, String projectexp) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.password = password;
        this.familiardomain = familiarDomain;
        this.projectexp = projectexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.projectExp
     *
     * @return the value of sys_user.projectExp
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getProjectexp() {
        return projectexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.projectExp
     *
     * @param projectexp the value for sys_user.projectExp
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setProjectexp(String projectexp) {
        this.projectexp = projectexp == null ? null : projectexp.trim();
    }

}