package cn.edu.buaa.rec.model;

public class UsecaseData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_data.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_data.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_data.data_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long dataId;

    public UsecaseData() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_data.id
     *
     * @return the value of usecase_data.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_data.id
     *
     * @param id the value for usecase_data.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_data.usecase_id
     *
     * @return the value of usecase_data.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_data.usecase_id
     *
     * @param usecaseId the value for usecase_data.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_data.data_id
     *
     * @return the value of usecase_data.data_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_data.data_id
     *
     * @param dataId the value for usecase_data.data_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}