package cn.edu.buaa.rec.model;

public class UsecaseBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_business.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    public UsecaseBusiness() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_business.id
     *
     * @return the value of usecase_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_business.id
     *
     * @param id the value for usecase_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_business.usecase_id
     *
     * @return the value of usecase_business.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_business.usecase_id
     *
     * @param usecaseId the value for usecase_business.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_business.business_id
     *
     * @return the value of usecase_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_business.business_id
     *
     * @param businessId the value for usecase_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }
}