package cn.edu.buaa.rec.model;

public class UserProject {

    private Long id;

    private Long userId;

    private Long projectId;

    private Integer isapproved;

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    @Override
    public String toString() {
        return "UserProject{" +
                "id=" + id +
                ", userId=" + userId +
                ", projectId=" + projectId +
                ", isapproved=" + isapproved +
                ", explanation='" + explanation + '\'' +
                '}';
    }

    public UserProject(Long id, Long userId, Long projectId, Integer isapproved, String explanation) {
        this.id = id;
        this.userId = userId;
        this.projectId = projectId;
        this.isapproved = isapproved;
        this.explanation = explanation;
    }

    private String explanation;

    public UserProject() {
    }

    public UserProject(Long id, Long userId, Long projectId, Integer isapproved) {
        this.id = id;
        this.userId = userId;
        this.projectId = projectId;
        this.isapproved = isapproved;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.user_id
     *
     * @param userId the value for user_project.user_id
     *
     * @mbggenerated Mon Mar 05 21:11:02 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_project.project_id
     *
     * @return the value of user_project.project_id
     *
     * @mbggenerated Mon Mar 05 21:11:02 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_project.project_id
     *
     * @param projectId the value for user_project.project_id
     *
     * @mbggenerated Mon Mar 05 21:11:02 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Integer getIsapproved() {
        return isapproved;
    }

    public void setIsapproved(Integer isapproved) {
        this.isapproved = isapproved;
    }
}